//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLogin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        public int Id { get; set; }
        [DisplayName("Enter user name")]
        [Required(ErrorMessage ="Not empty for username")]
        public string Name { get; set; }
        [DataType(DataType.Password)]
        [DisplayName("Enter password")]
        [Required(ErrorMessage = "Not empty for password")]
        public string Description { get; set; }
        public string LoginErrorMessage { get; set; }

    }
}
